### ISSUE TITLE
OpenID-Connect authentication fails after a while

### ISSUE THREAD

**Issue by domq** [epfl-si/react.starterkit#1]
How to reproduce:

1. Check out [the `feature/meteor` branch](https://github.com/epfl-si/react.starterkit/tree/feature/meteor)
2. Run the Meteor server:
    ```
    meteor npm i
    meteor
    ```
3. Log in using the login button
4. Wait 15–30 minutes without touching anything
5. Browse https://localhost:3000/

Expected result: the UI should show up.

Actual result:

```
I20230517-19:04:48.499(2)? Exception while invoking method 'login' OPError: invalid_token (Token verification failed)
I20230517-19:04:48.500(2)?     at throwAuthenticateErrors (/home/pyrosaphire/repos/TPI/ATARI/node_modules/openid-client/lib/helpers/process_response.js:11:11)
I20230517-19:04:48.500(2)?     at processResponse (/home/pyrosaphire/repos/TPI/ATARI/node_modules/openid-client/lib/helpers/process_response.js:34:7)
I20230517-19:04:48.501(2)?     at Client.userinfo (/home/pyrosaphire/repos/TPI/ATARI/node_modules/openid-client/lib/client.js:1237:18)
I20230517-19:04:48.501(2)?     at processTicksAndRejections (internal/process/task_queues.js:95:5)
I20230517-19:04:48.501(2)?  => awaited here:
I20230517-19:04:48.502(2)?     at Function.Promise.await (/home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230517-19:04:48.502(2)?     at server/OIDC/UserInfo.ts:22:5
I20230517-19:04:48.502(2)?     at /home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20230517-19:04:48.502(2)?  => awaited here:
I20230517-19:04:48.503(2)?     at Function.Promise.await (/home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230517-19:04:48.503(2)?     at server/OIDC/OIDC.ts:13:19
I20230517-19:04:48.504(2)?     at /home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20230517-19:04:48.505(2)?  => awaited here:
I20230517-19:04:48.507(2)?     at Function.Promise.await (/home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230517-19:04:48.507(2)?     at packages/accounts-base/accounts_server.js:1525:11
I20230517-19:04:48.508(2)?     at /home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20230517-19:04:48.508(2)?  => awaited here:
I20230517-19:04:48.508(2)?     at Function.Promise.await (/home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230517-19:04:48.509(2)?     at packages/accounts-base/accounts_server.js:653:7
I20230517-19:04:48.512(2)?     at /home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20230517-19:04:48.515(2)?  => awaited here:
I20230517-19:04:48.516(2)?     at Function.Promise.await (/home/pyrosaphire/.meteor/packages/promise/.0.12.2.1l90419.x6xt++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20230517-19:04:48.516(2)?     at getCurrentMethodInvocationResult (packages/ddp-server/livedata_server.js:781:32)
I20230517-19:04:48.516(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
I20230517-19:04:48.517(2)?     at packages/ddp-server/livedata_server.js:791:46
I20230517-19:04:48.517(2)?     at new Promise (<anonymous>)
I20230517-19:04:48.517(2)?     at Session.method (packages/ddp-server/livedata_server.js:739:23)
I20230517-19:04:48.517(2)?     at packages/ddp-server/livedata_server.js:603:43
```

**Comment by domq** [comment]
This stack trace suggests [a bug in `server/OIDC/UserInfo.ts`](https://github.com/epfl-si/react.starterkit/blob/feature/meteor/server/OIDC/UserInfo.ts), perhaps after Keycloak's JWS signing keys roll over?
